stages:
  - lint
  - build
  - test
  - docker
  - delivery


variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/app"


lint:
  stage: lint
  image: python:3.14-slim
  script:
    - pip install ruff
    - ruff check .


build:
  stage: build
  image: python:3.14-slim
  script:
    - pip install -r requirements.txt


test:
  stage: test
  image: docker:27
  script:
    - docker compose -f docker-compose.test.yml up -d --build
    - docker compose -f docker-compose.test.yml logs --follow
    - docker compose -f docker-compose.test.yml down


docker_build:
  stage: docker
  image: docker:27
  script:
    - docker build -t "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" .


delivery:
  stage: delivery
  image: docker:27
  only:
    - main
  script:
    - docker build -t "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker tag "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$DOCKER_IMAGE:latest"
