stages:
  - lint
  - build
  - test
  - docker


variables:
  DOCKER_IMAGE: "chatbot/app"


lint:
  stage: lint
  image: python:3.14-slim
  script:
    - pip install ruff
    - ruff check .


build:
  stage: build
  image: python:3.14-slim
  script:
    - pip install -r requirements.txt


test:
  stage: test
  image: docker:27
  script:
    - docker compose -f "docker-compose.test.yml" up --abort-on-container-exit --build
    - docker compose -f "docker-compose.test.yml" down


docker_build:
  stage: docker
  image: docker:27
  script:
    - docker build -t "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" .
