stages:
  - lint
  - build
  - test
  - docker
  - delivery


variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/app"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""


lint:
  stage: lint
  image: python:3.14-slim
  script:
    - pip install ruff
    - ruff check .


build:
  stage: build
  image: python:3.14-slim
  script:
    - pip install -r requirements.txt


test:
  stage: test
  image: docker:27
  services:
    - docker:27-dind
  script:
    - docker compose -f docker-compose.test.yml up -d --build
    - until curl -f http://localhost:8002/docs; do echo "Waiting for vector_api..."; sleep 2; done
    - docker compose -f docker-compose.test.yml logs --follow
    - docker compose -f docker-compose.test.yml down


docker_build:
  stage: docker
  image: docker:27
  services:
    - docker:27-dind
  script:
    - docker build -t "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" .


delivery:
  stage: delivery
  image: docker:27
  only:
    - main
  services:
    - docker:27-dind
  script:
    - docker build -t "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker tag "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$DOCKER_IMAGE:latest"
